### ISSUE TITLE
TypeError unexpected argument 'paste_back'

### ISSUE THREAD

**Issue by garydash** [Ynn/sd-webui-faceswap#10]
Hello!
I am thankful for your work and assistance.
After generating the image I am receiving the following text:

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:42<00:00,  2.13s/it]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}| 20/20 [00:26<00:00,  1.81s/it]
find model: /.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: .insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
set det-size: (640, 640)
Error running postprocess_batch: Stable Difusion\extensions\sd-webui-faceswap\scripts\faceswap.py
Traceback (most recent call last):
  File "\Pyton\Stable Difusion\modules\scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "\Pyton\Stable Difusion\extensions\sd-webui-faceswap\scripts\faceswap.py", line 117, in postprocess_image
    result = swap_face(self.source, image, faces_index = self.faces_index, model=self.model, upscale_options=self.upscale_options)
  File "\Pyton\Stable Difusion\extensions\sd-webui-faceswap\scripts\swapper.py", line 123, in swap_face
    result = face_swapper.get(
TypeError: Attribute.get() got an unexpected keyword argument 'paste_back'

I am kind of stuck in this part, i've tried with different models, but not success at the time, do you have any suggestion?
Thanks a lot in advance :)

**Comment by ronbere** [comment]
same here

**Comment by Ynn** [comment]
As a quick fix, you can try to remove the extra arg line 141.

```python
            if target_face is not None:
                result = face_swapper.get(
                    result, target_face, source_face
                )
```

Will investigate more on this later.

**Comment by ronbere** [comment]
what file?

**Comment by garydash** [comment]
> ```python
>   if target_face is not None:
>                 result = face_swapper.get(
>                     result, target_face, source_face
>                 )
> ```

Hi! Just to report I did the changes and this is the new error displayed:

 result = face_swapper.get(
TypeError: Landmark.get() takes 3 positional arguments but 4 were given

I'll keep an eye on this. Thanks in advance again for your answers.
PS: I am new to Github so I accidentaly close the ticket after every reply but I reopen immediatly, sorry for this (ー_ー﹡;  )

**Comment by garydash** [comment]
> 

No, just erase the argument paste back ;)

**Comment by garydash** [comment]
> if target_face is not None: result = face_swapper.get( result, target_face, source_face, paste_back=True
> 
> have this on line 141...delete all??

No, just erase the paste_back ex arg ;)

**Comment by ronbere** [comment]
working thanks !!!

**Comment by garydash** [comment]
> working thanks !!!

Nice @ronbere n.n, if the workaround worked can you share a copy of your code to do a quick comparison? Thanks in advance.

**Comment by ronbere** [comment]
what do u mean? sorry my english are not very good

**Comment by Ynn** [comment]
I am not really sure that the workaround does not have huge side effects on performance. I need to check more on this.
