### ISSUE TITLE
AttributeError: 'int' object has no attribute 'strip'

### ISSUE THREAD

**Issue by CGMikeG** [Ynn/sd-webui-faceswap#11]
I keep getting below error

Error running process: E:\STABLEDIFFUSION2\SD2\extensions\sd-webui-faceswap\scripts\faceswap.py
Traceback (most recent call last):
  File "E:\STABLEDIFFUSION2\SD2\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "E:\STABLEDIFFUSION2\SD2\extensions\sd-webui-faceswap\scripts\faceswap.py", line 98, in process
    self.faces_index = {int(x) for x in faces_index.strip(",").split(",") if x.isnumeric()}
AttributeError: 'int' object has no attribute 'strip'

**Comment by Ynn** [comment]
Try to put 0 in comma separated face number.
