### ISSUE TITLE
ModuleNotFoundError: No module named 'stegano'

### ISSUE THREAD

**Issue by swumagic** [Ynn/sd-webui-faceswap#15]
Error loading script: faceswap.py
Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\StableDiffusion\sdwebui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-faceswap\scripts\faceswap.py", line 15, in <module>
    from scripts.swapper import UpscaleOptions, swap_face, ImageResult
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-faceswap\scripts\swapper.py", line 11, in <module>
    from stegano import lsb as l
ModuleNotFoundError: No module named 'stegano'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

2023-06-17 23:17:53,409 - FaceSwap - INFO - FaceSwap v0.0.9
Error loading script: swapper.py
Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\StableDiffusion\sdwebui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-faceswap\scripts\swapper.py", line 11, in <module>
    from stegano import lsb as l
ModuleNotFoundError: No module named 'stegano'

**Comment by Ynn** [comment]
I noticed that after first install, the extension does not find the dependencies. Often a simple restart of automatic 1111 is sufficient. Tell me if it's not the case.

**Comment by swumagic** [comment]
pip install stegano,it ok
