### ISSUE TITLE
ModuleNotFoundError: No module named 'insightface'

### ISSUE THREAD

**Issue by swumagic** [Ynn/sd-webui-faceswap#4]
Error loading script: faceswap.py
Traceback (most recent call last):
  File "K:\StableDiffusion\sdwebui\modules\scripts.py", line 263, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "K:\StableDiffusion\sdwebui\modules\script_loading.py", line 10, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-faceswap\scripts\faceswap.py", line 11, in <module>
    from scripts.swapper import swap_face
  File "K:\StableDiffusion\sdwebui\extensions\sd-webui-faceswap\scripts\swapper.py", line 4, in <module>
    import insightface
ModuleNotFoundError: No module named 'insightface'

**Comment by Ynn** [comment]
i am bit puzzled, could be related to install.py. I don't really use windows atm

Anyway, first try to restart sd. If it does not work try to install dependencies manually : 

in sd root :
```shell
.\venv\Scripts\activate
cd .\extensions\sd-webui-faceswap\
pip install -r requirements.txt
```

**Comment by swumagic** [comment]
K:\StableDiffusion\sdwebui\py310>pip install insightface
Collecting insightface
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in k:\stablediffusion\sdwebui\py310\lib\site-packages (from insightface) (1.23.5)
Collecting onnx (from insightface)
  Using cached onnx-1.14.0-cp310-cp310-win_amd64.whl (13.3 MB)
Requirement already satisfied: tqdm in k:\stablediffusion\sdwebui\py310\lib\site-packages (from insightface) (4.65.0)
Requirement already satisfied: requests in k:\stablediffusion\sdwebui\py310\lib\site-packages (from insightface) (2.31.0)
Requirement already satisfied: matplotlib in k:\stablediffusion\sdwebui\py310\lib\site-packages (from insightface) (3.7.1)
Requirement already satisfied: Pillow in k:\stablediffusion\sdwebui\py310\lib\site-packages (from insightface) (9.5.0)
Requirement already satisfied: scipy in k:\stablediffusion\sdwebui\py310\lib\site-packages (from insightface) (1.10.1)
Requirement already satisfied: scikit-learn in k:\stablediffusion\sdwebui\py310\lib\site-packages (from insightface) (1.2.2)
Requirement already satisfied: scikit-image in k:\stablediffusion\sdwebui\py310\lib\site-packages (from insightface) (0.20.0)
Collecting easydict (from insightface)
  Using cached easydict-1.10-py3-none-any.whl
Requirement already satisfied: cython in k:\stablediffusion\sdwebui\py310\lib\site-packages (from insightface) (0.29.34)
Collecting albumentations (from insightface)
  Using cached albumentations-1.3.1-py3-none-any.whl (125 kB)
Collecting prettytable (from insightface)
  Using cached prettytable-3.7.0-py3-none-any.whl (27 kB)
Requirement already satisfied: PyYAML in k:\stablediffusion\sdwebui\py310\lib\site-packages (from albumentations->insightface) (6.0)
Collecting qudida>=0.0.4 (from albumentations->insightface)
  Using cached qudida-0.0.4-py3-none-any.whl (3.5 kB)
Requirement already satisfied: opencv-python-headless>=4.1.1 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from albumentations->insightface) (4.7.0.72)
Requirement already satisfied: networkx>=2.8 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from scikit-image->insightface) (3.0)
Requirement already satisfied: imageio>=2.4.1 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from scikit-image->insightface) (2.28.0)
Requirement already satisfied: tifffile>=2019.7.26 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from scikit-image->insightface) (2023.4.12)
Requirement already satisfied: PyWavelets>=1.1.1 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from scikit-image->insightface) (1.4.1)
Requirement already satisfied: packaging>=20.0 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from scikit-image->insightface) (23.1)
Requirement already satisfied: lazy_loader>=0.1 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from scikit-image->insightface) (0.2)
Requirement already satisfied: contourpy>=1.0.1 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from matplotlib->insightface) (1.0.7)
Requirement already satisfied: cycler>=0.10 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from matplotlib->insightface) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from matplotlib->insightface) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from matplotlib->insightface) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from matplotlib->insightface) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from matplotlib->insightface) (2.8.2)
Requirement already satisfied: protobuf>=3.20.2 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from onnx->insightface) (3.20.3)
Requirement already satisfied: typing-extensions>=3.6.2.1 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from onnx->insightface) (4.4.0)
Requirement already satisfied: wcwidth in k:\stablediffusion\sdwebui\py310\lib\site-packages (from prettytable->insightface) (0.2.6)
Requirement already satisfied: charset-normalizer<4,>=2 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from requests->insightface) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from requests->insightface) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from requests->insightface) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from requests->insightface) (2022.12.7)
Requirement already satisfied: joblib>=1.1.1 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from scikit-learn->insightface) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from scikit-learn->insightface) (3.1.0)
Requirement already satisfied: colorama in k:\stablediffusion\sdwebui\py310\lib\site-packages (from tqdm->insightface) (0.4.6)
Requirement already satisfied: six>=1.5 in k:\stablediffusion\sdwebui\py310\lib\site-packages (from python-dateutil>=2.7->matplotlib->insightface) (1.16.0)
Building wheels for collected packages: insightface
  Building wheel for insightface (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for insightface (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [192 lines of output]
      WARNING: pandoc not enabled
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\insightface
      copying insightface\__init__.py -> build\lib.win-amd64-cpython-310\insightface
      creating build\lib.win-amd64-cpython-310\insightface\app
      copying insightface\app\common.py -> build\lib.win-amd64-cpython-310\insightface\app
      copying insightface\app\face_analysis.py -> build\lib.win-amd64-cpython-310\insightface\app
      copying insightface\app\mask_renderer.py -> build\lib.win-amd64-cpython-310\insightface\app
      copying insightface\app\__init__.py -> build\lib.win-amd64-cpython-310\insightface\app
      creating build\lib.win-amd64-cpython-310\insightface\commands
      copying insightface\commands\insightface_cli.py -> build\lib.win-amd64-cpython-310\insightface\commands
      copying insightface\commands\model_download.py -> build\lib.win-amd64-cpython-310\insightface\commands
      copying insightface\commands\rec_add_mask_param.py -> build\lib.win-amd64-cpython-310\insightface\commands
      copying insightface\commands\__init__.py -> build\lib.win-amd64-cpython-310\insightface\commands
      creating build\lib.win-amd64-cpython-310\insightface\data
      copying insightface\data\image.py -> build\lib.win-amd64-cpython-310\insightface\data
      copying insightface\data\pickle_object.py -> build\lib.win-amd64-cpython-310\insightface\data
      copying insightface\data\rec_builder.py -> build\lib.win-amd64-cpython-310\insightface\data
      copying insightface\data\__init__.py -> build\lib.win-amd64-cpython-310\insightface\data
      creating build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\arcface_onnx.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\attribute.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\inswapper.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\landmark.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\model_store.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\model_zoo.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\retinaface.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\scrfd.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      copying insightface\model_zoo\__init__.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
      creating build\lib.win-amd64-cpython-310\insightface\thirdparty
      copying insightface\thirdparty\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty
      creating build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\constant.py -> build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\download.py -> build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\face_align.py -> build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\filesystem.py -> build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\storage.py -> build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\transform.py -> build\lib.win-amd64-cpython-310\insightface\utils
      copying insightface\utils\__init__.py -> build\lib.win-amd64-cpython-310\insightface\utils
      creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d
      copying insightface\thirdparty\face3d\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d      creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\io.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\light.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\render.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\transform.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\vis.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      copying insightface\thirdparty\face3d\mesh\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
      creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\io.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\light.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\render.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\transform.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\vis.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
      copying insightface\thirdparty\face3d\mesh_numpy\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
      creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
      copying insightface\thirdparty\face3d\morphable_model\fit.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
      copying insightface\thirdparty\face3d\morphable_model\load.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
      copying insightface\thirdparty\face3d\morphable_model\morphabel_model.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
      copying insightface\thirdparty\face3d\morphable_model\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
      running egg_info
      writing insightface.egg-info\PKG-INFO
      writing dependency_links to insightface.egg-info\dependency_links.txt
      writing entry points to insightface.egg-info\entry_points.txt
      writing requirements to insightface.egg-info\requires.txt
      writing top-level names to insightface.egg-info\top_level.txt
      reading manifest file 'insightface.egg-info\SOURCES.txt'
      writing manifest file 'insightface.egg-info\SOURCES.txt'
      K:\StableDiffusion\sdwebui\py310\lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'insightface.thirdparty.face3d.mesh.cython' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'insightface.thirdparty.face3d.mesh.cython' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'insightface.thirdparty.face3d.mesh.cython' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'insightface.thirdparty.face3d.mesh.cython' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)
      K:\StableDiffusion\sdwebui\py310\lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'insightface.data.images' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'insightface.data.images' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'insightface.data.images' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'insightface.data.images' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)
      K:\StableDiffusion\sdwebui\py310\lib\site-packages\setuptools\command\build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'insightface.data.objects' as data is deprecated, please list it in `packages`.
          !!


          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'insightface.data.objects' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.

          'insightface.data.objects' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).

          Please make sure that 'insightface.data.objects' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).

          You can read more about "package discovery" and "data files" on setuptools
          documentation page.


      !!

        check.warn(importable)
      creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      creating build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\Tom_Hanks_54745.png -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\mask_black.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\mask_blue.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\mask_green.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\mask_white.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      copying insightface\data\images\t1.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
      creating build\lib.win-amd64-cpython-310\insightface\data\objects
      copying insightface\data\objects\meanshape_68.pkl -> build\lib.win-amd64-cpython-310\insightface\data\objects
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core.h -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.c -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.pyx -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      copying insightface\thirdparty\face3d\mesh\cython\setup.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
      running build_ext
      building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      creating build\temp.win-amd64-cpython-310\Release\insightface
      creating build\temp.win-amd64-cpython-310\Release\insightface\thirdparty
      creating build\temp.win-amd64-cpython-310\Release\insightface\thirdparty\face3d
      creating build\temp.win-amd64-cpython-310\Release\insightface\thirdparty\face3d\mesh
      creating build\temp.win-amd64-cpython-310\Release\insightface\thirdparty\face3d\mesh\cython
      K:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iinsightface/thirdparty/face3d/mesh/cython -IK:\StableDiffusion\sdwebui\py310\lib\site-packages\numpy\core\include -IK:\StableDiffusion\sdwebui\py310\include -IK:\StableDiffusion\sdwebui\py310\Include -IK:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\include -IK:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\include -IK:\VR\visualstudio2022\Community\VC\Auxiliary\VS\include -IK:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\include "-IK:\Windows Kits\10\Include\10.0.22000.0\cppwinrt" "-IK:\Windows Kits\10\Include\10.0.22000.0\shared" "-IK:\Windows Kits\10\Include\10.0.22000.0\ucrt" "-IK:\Windows Kits\10\Include\10.0.22000.0\um" "-IK:\Windows Kits\10\Include\10.0.22000.0\winrt" /EHsc /Tpinsightface/thirdparty/face3d/mesh/cython/mesh_core.cpp /Fobuild\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython/mesh_core.obj
      mesh_core.cpp
      insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(147): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
      insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(147): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
      insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(210): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
      insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(210): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
      insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(294): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
      insightface/thirdparty/face3d/mesh/cython/mesh_core.cpp(294): warning C4244: “=”: 从“int”转换到“float”，可能丢失数据
      K:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -Iinsightface/thirdparty/face3d/mesh/cython -IK:\StableDiffusion\sdwebui\py310\lib\site-packages\numpy\core\include -IK:\StableDiffusion\sdwebui\py310\include -IK:\StableDiffusion\sdwebui\py310\Include -IK:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\include -IK:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\include -IK:\VR\visualstudio2022\Community\VC\Auxiliary\VS\include -IK:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\include "-IK:\Windows Kits\10\Include\10.0.22000.0\cppwinrt" "-IK:\Windows Kits\10\Include\10.0.22000.0\shared" "-IK:\Windows Kits\10\Include\10.0.22000.0\ucrt" "-IK:\Windows Kits\10\Include\10.0.22000.0\um" "-IK:\Windows Kits\10\Include\10.0.22000.0\winrt" /EHsc /Tpinsightface/thirdparty/face3d/mesh/cython/mesh_core_cython.cpp /Fobuild\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.obj
      mesh_core_cython.cpp
      K:\StableDiffusion\sdwebui\py310\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
      K:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:K:\StableDiffusion\sdwebui\py310\libs /LIBPATH:K:\StableDiffusion\sdwebui\py310 /LIBPATH:K:\StableDiffusion\sdwebui\py310\PCbuild\amd64 /LIBPATH:K:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\ATLMFC\lib\x64 /LIBPATH:K:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\lib\x64 /LIBPATH:K:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\lib\x64 "/LIBPATH:K:\Windows Kits\10\Lib\10.0.22000.0\ucrt\x64" "/LIBPATH:K:\Windows Kits\10\Lib\10.0.22000.0\ucrt_enclave\x64" "/LIBPATH:K:\Windows Kits\10\Lib\10.0.22000.0\um\x64" /EXPORT:PyInit_mesh_core_cython build\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython/mesh_core.obj build\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython/mesh_core_cython.obj /OUT:build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.cp310-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython\mesh_core_cython.cp310-win_amd64.lib
        正在创建库 build\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython\mesh_core_cython.cp310-win_amd64.lib 和对象 build\temp.win-amd64-cpython-310\Release\insightface/thirdparty/face3d/mesh/cython\mesh_core_cython.cp310-win_amd64.exp
      正在生成代码
      已完成代码的生成
      LINK : fatal error LNK1158: 无法运行“rc.exe”
      error: command 'K:\\VR\\visualstudio2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX86\\x64\\link.exe' failed with exit code 1158
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for insightface
Failed to build insightface
ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects

**Comment by mocmocmoc** [comment]
> ERROR: Failed building wheel for insightface
> ERROR: Could not build wheels for insightface

Install Microsoft C++ Build Tools https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by swumagic** [comment]
Thank you very much! I've been previously installed VS2022 software。But still the above problems, other software VS2022 no problem with it

**Comment by swumagic** [comment]
my PC is win10 64 - bit system。Installation environment：path: choose， K:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX86\x64, 
OR  K:\VR\visualstudio2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64？
I suspect I set wrong  path here.

**Comment by kengher** [comment]
> > ERROR: Failed building wheel for insightface
> > ERROR: Could not build wheels for insightface
> 
> Install Microsoft C++ Build Tools https://visualstudio.microsoft.com/visual-cpp-build-tools/

I just confirmed this worked for me too! Thanks!
