### ISSUE TITLE
ValueError: Coordinate 'right' is less than 'left'

### ISSUE THREAD

**Issue by BursonHandsom** [Ynn/sd-webui-faceswap#6]
sumarize as title

**Comment by Ynn** [comment]
Could you provide more details on when it occured (txt2img, img2img) and give the error stacktrace

**Comment by BursonHandsom** [comment]
@Ynn In t2i,when i enable the faceswap,it appears.
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /root/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
/root/miniconda3/lib/python3.10/site-packages/insightface/utils/transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
Error running postprocess_batch: /root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-faceswap/scripts/faceswap.py
Traceback (most recent call last):
  File "/root/autodl-tmp/stable-diffusion-webui/modules/scripts.py", line 496, in postprocess_image
    script.postprocess_image(p, pp, *script_args)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-faceswap/scripts/faceswap.py", line 79, in postprocess_image
    result = swap_face(self.source, image, faces_index = self.faces_index, model=self.model)
  File "/root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-faceswap/scripts/swapper.py", line 40, in swap_face
    face_swapper = insightface.model_zoo.get_model(
  File "/root/miniconda3/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 96, in get_model
    model = router.get_model(providers=providers, provider_options=provider_options)
  File "/root/miniconda3/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 40, in get_model
    session = PickableInferenceSession(self.onnx_file, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/insightface/model_zoo/model_zoo.py", line 25, in __init__
    super().__init__(model_path, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/root/miniconda3/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 424, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /root/autodl-tmp/stable-diffusion-webui/extensions/sd-webui-faceswap/models/inswapper_128.onnx failed:Protobuf parsing failed.

**Comment by Ynn** [comment]
It seems there is a problem with the model you are using (may be try to download once again). I don't think it's directly related to this extension or that i can do anything about it right now.
